//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarrialSurEntities1 : DbContext
    {
        public BarrialSurEntities1()
            : base("name=BarrialSurEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbitro> Arbitro { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Campeonato> Campeonato { get; set; }
        public virtual DbSet<Campeonato_Equipo> Campeonato_Equipo { get; set; }
        public virtual DbSet<Dirigente> Dirigente { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Gol_jugador_partido> Gol_jugador_partido { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Partido_Equipo> Partido_Equipo { get; set; }
        public virtual DbSet<Partido_Jugador> Partido_Jugador { get; set; }
        public virtual DbSet<Pase> Pase { get; set; }
        public virtual DbSet<tablaposicion> tablaposicion { get; set; }
        public virtual DbSet<Vocal> Vocal { get; set; }
    }
}
