//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dirigente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dirigente()
        {
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int Id_dirigente { get; set; }
        public string ced_dirigente { get; set; }
        public string nom_dirigente { get; set; }
        public string apelli_dirigente { get; set; }
        public string dir_dirigente { get; set; }
        public string telf_dirigente { get; set; }
        public string Fullname { get { return string.Format("{0}{1}{2}", this.nom_dirigente, " ", this.apelli_dirigente); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
