//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            foto_equipo = "../../Repositorio/default.png";

            this.Campeonato_Equipo = new HashSet<Campeonato_Equipo>();
            this.Partido_Equipo = new HashSet<Partido_Equipo>();
            this.Jugador = new HashSet<Jugador>();
            this.Pase = new HashSet<Pase>();
            this.tablaposicion = new HashSet<tablaposicion>();
            this.Partido = new HashSet<Partido>();
            this.Partido1 = new HashSet<Partido>();
        }
    
        public int Id_Equipo { get; set; }
        public string nom_equipo { get; set; }
        public string color_equipo { get; set; }
        public System.DateTime fundacion { get; set; }
        public string foto_equipo { get; set; }
        public string liga { get; set; }
        public string serie { get; set; }
        public string Estado_equipo { get; set; }
        public Nullable<int> id_dirigente { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campeonato_Equipo> Campeonato_Equipo { get; set; }
        public virtual Dirigente Dirigente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido_Equipo> Partido_Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador> Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pase> Pase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tablaposicion> tablaposicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido> Partido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido> Partido1 { get; set; }
    }
}
