//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gol_jugador_partido
    {
        public int id_gol { get; set; }
        public Nullable<int> id_partido { get; set; }
        public Nullable<int> id_jugador { get; set; }
        public Nullable<int> goles { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
