//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            foto_jugador = "~/ImgJugador/default.png";
            this.Gol_jugador_partido = new HashSet<Gol_jugador_partido>();
            this.Partido_Jugador = new HashSet<Partido_Jugador>();
            this.Pase = new HashSet<Pase>();
        }
    
        public int Id_jugador { get; set; }
        public string ced_jugador { get; set; }
        public string nom_jugador { get; set; }
        public string apell_jugador { get; set; }
        public System.DateTime fechaNac_jugador { get; set; }
        public int carnet_jugador { get; set; }
        public string foto_jugador { get; set; }
        public System.DateTime fecha_filiacion { get; set; }
        public string estado_civil { get; set; }
        public string instruccion { get; set; }
        public string profesion { get; set; }
        public string provincia { get; set; }
        public string parroquia { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public string Fullname { get { return string.Format("{0}{1}{2}", this.nom_jugador, " ", this.apell_jugador); } }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }


        public virtual Equipo Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gol_jugador_partido> Gol_jugador_partido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido_Jugador> Partido_Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pase> Pase { get; set; }
    }
}
