//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int id_pagos { get; set; }
        public Nullable<int> id_part_jugador { get; set; }
        public Nullable<int> id_part_equipo { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Partido_Equipo Partido_Equipo { get; set; }
        public virtual Partido_Jugador Partido_Jugador { get; set; }
    }
}
