//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partido()
        {
            this.Gol_jugador_partido = new HashSet<Gol_jugador_partido>();
            this.Partido_Equipo = new HashSet<Partido_Equipo>();
            this.Partido_Jugador = new HashSet<Partido_Jugador>();
        }
    
        public int id_partido { get; set; }
        public string Jornada { get; set; }
        public Nullable<int> Equipo_visitante { get; set; }
        public Nullable<int> Equipo_local { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> gol_local { get; set; }
        public Nullable<int> gol_visita { get; set; }
        public Nullable<int> Juez_Linea1 { get; set; }
        public Nullable<int> Juez_Linea2 { get; set; }
        public Nullable<int> Juez_Central { get; set; }
        public Nullable<int> Vocal1 { get; set; }
        public Nullable<int> Vocal2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gol_jugador_partido> Gol_jugador_partido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido_Equipo> Partido_Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partido_Jugador> Partido_Jugador { get; set; }
        public virtual Arbitro Arbitro { get; set; }
        public virtual Arbitro Arbitro1 { get; set; }
        public virtual Arbitro Arbitro2 { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        public virtual Vocal Vocal { get; set; }
        public virtual Vocal Vocal3 { get; set; }
    }
}
