//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LigaSurTulcan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablaposicion
    {
        public int id_posicion { get; set; }
        public Nullable<int> pj { get; set; }
        public Nullable<int> pg { get; set; }
        public Nullable<int> pe { get; set; }
        public Nullable<int> pp { get; set; }
        public Nullable<int> gf { get; set; }
        public Nullable<int> gc { get; set; }
        public Nullable<int> gd { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<int> id_equipo { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
